version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: weather_t
    description: "Model representing weather data"
    columns:
      - name: date
        description: "Date of the weather observation"
        tests:
          - not_null
      - name: temperature_2m
        description: "Temperature at 2m above ground level"
        tests:
          - not_null
      - name: relative_humidity_2m
        description: "Relative humidity at 2m above ground level"
        tests:
          - not_null
      - name: precipitation
        description: "Precipitation amount"
        tests:
          - not_null
      - name: rain
        description: "Rainfall amount"
        tests:
          - not_null
      - name: snowfall
        description: "Snowfall amount"
        tests:
          - not_null
      - name: surface_pressure
        description: "Surface pressure"
        tests:
          - not_null
      - name: cloud_cover
        description: "Cloud cover percentage"
        tests:
          - not_null
      - name: wind_speed_10m
        description: "Wind speed at 10m above ground level"
        tests:
          - not_null
      - name: soil_temperature_0_to_7cm
        description: "Soil temperature at 0-7cm depth"
        tests:
          - not_null
      - name: soil_moisture_0_to_7cm
        description: "Soil moisture at 0-7cm depth"
        tests:
          - not_null
      - name: is_day
        description: "Indicator for daytime (1) or nighttime (0)"
        tests:
          - not_null
      - name: sunshine_duration
        description: "Sunshine duration"
        tests:
          - not_null
      - name: City
        description: "City where the weather observation was recorded"
        tests:
          - not_null

  - name: air_quality
    description: "Model representing air quality data"
    columns:
      - name: date
        description: "Date of the air quality observation"
        tests:
          - not_null
      - name: city
        description: "City where the air quality observation was recorded"
        tests:
          - not_null
      - name: pm10
        description: "PM10 pollutant concentration"
        tests:
          - not_null
      - name: pm2_5
        description: "PM2.5 pollutant concentration"
        tests:
          - not_null
      - name: carbon_monoxide
        description: "Carbon monoxide pollutant concentration"
        tests:
          - not_null
      - name: nitrogen_dioxide
        description: "Nitrogen dioxide pollutant concentration"
        tests:
          - not_null
      - name: ozone
        description: "Ozone pollutant concentration"
        tests:
          - not_null
      - name: dust
        description: "Dust pollutant concentration"
        tests:
          - not_null
      - name: uv_index
        description: "UV index"
        tests:
          - not_null
      - name: ammonia
        description: "Ammonia pollutant concentration"
        tests:
          - not_null
      - name: alder_pollen
        description: "Alder pollen concentration"
        tests:
          - not_null
      - name: grass_pollen
        description: "Grass pollen concentration"
        tests:
          - not_null
      - name: ragweed_pollen
        description: "Ragweed pollen concentration"
        tests:
          - not_null
      - name: european_aqi
        description: "European Air Quality Index"
        tests:
          - not_null

  - name: temp_humi_corr
    description: "Model representing correlations between temperature, humidity, and weather factors"
    columns:
      - name: date
        description: "Date of the weather observation"
        tests:
          - not_null
      - name: temperature_2m
        description: "Temperature at 2m above ground level"
        tests:
          - not_null
      - name: relative_humidity_2m
        description: "Relative humidity at 2m above ground level"
        tests:
          - not_null
      - name: cloud_cover
        description: "Cloud cover percentage"
        tests:
          - not_null
      - name: wind_speed_10m
        description: "Wind speed at 10m above ground level"
        tests:
          - not_null
      - name: sunshine_duration
        description: "Sunshine duration"
        tests:
          - not_null

  - name: aqi
    description: "Model representing Air Quality Index (AQI) calculations"
    columns:
      - name: date
        description: "Date of the air quality observation"
        tests:
          - not_null
      - name: temperature_2m
        description: "Temperature at 2m above ground level"
        tests:
          - not_null
      - name: relative_humidity_2m
        description: "Relative humidity at 2m above ground level"
        tests:
          - not_null
      - name: cloud_cover
        description: "Cloud cover percentage"
        tests:
          - not_null
      - name: wind_speed_10m
        description: "Wind speed at 10m above ground level"
        tests:
          - not_null
      - name: sunshine_duration
        description: "Sunshine duration"
        tests:
          - not_null

  - name: date_details
    description: "Model representing weather and air quality date details"
    columns:
      - name: date
        description: "Date of the observation"
        tests:
          - not_null
      - name: day_of_week
        description: "Day of the week (1 = Sunday, 2 = Monday, ...)"
        tests:
          - not_null
      - name: quarter
        description: "Quarter of the year (1 = Jan-Mar, 2 = Apr-Jun, ...)"
        tests:
          - not_null
      - name: month_name
        description: "Name of the month (e.g., January, February, ...)"
        tests:
          - not_null

  - name: rainfall_snowfall_quarter
    description: "Model representing rainfall and snowfall by quarter"
    columns:
      - name: weather_date
        description: "Date of the weather observation"
        tests:
          - not_null
      - name: rain
        description: "Rainfall amount"
        tests:
          - not_null
      - name: snowfall
        description: "Snowfall amount"
        tests:
          - not_null
      - name: quarter
        description: "Quarter of the year (1 = Jan-Mar, 2 = Apr-Jun, ...)"
        tests:
          - not_null
      - name: month_name
        description: "Name of the month (e.g., January, February, ...)"
        tests:
          - not_null
